templates:
  - "templates/web.template.yml"
  - "templates/web.ratelimited.template.yml"
  - "templates/env.yml"

expose:
  - "80:80"

params:
  ## Which Git revision should this container use? (default: tests-passed)
  version: tests-passed

volumes:
  - volume:
      host: /srv/marathon-efs/discourse-production/shared/web-only
      guest: /shared
  - volume:
      host: /srv/marathon-efs/discourse-production/shared/web-only/log/var-log
      guest: /var/log

## The docker manager plugin allows you to one-click upgrade Discouse
## http://discourse.example.com/admin/docker
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - mkdir -p plugins
          - git clone https://github.com/discourse/discourse-akismet.git
          - git clone https://github.com/mozilla/discourse-mozilla-iam.git
          - git clone https://github.com/mozilla/discourse-email-all.git
          - git clone https://github.com/mozilla/discourse-expose-emails-in.git
          - git clone https://github.com/mozilla/discourse-post-read-email.git
          - git clone https://github.com/discourse/discourse-solved.git
run:
  - exec: echo "Beginning of custom commands"

  - replace:
      filename: "/etc/nginx/conf.d/discourse.conf"
      from: "location @discourse {"
      to: |+
        location @discourse {
        add_header Strict-Transport-Security max-age=15768000;
        add_header Content-Security-Policy "default-src 'self' https://www.youtube.com https://player.vimeo.com https://discourse.production.paas.mozilla.community https://cdn-production.discourse.mozilla-community.org; script-src https://discourse.production.paas.mozilla.community https://cdn-production.discourse.mozilla-community.org https://rum-static.pingdom.net https://www.googletagmanager.com https://tagmanager.google.com https://www.google-analytics.com 'self' 'unsafe-inline' 'unsafe-eval'; style-src https://discourse.production.paas.mozilla.community https://code.cdn.mozilla.net https://fonts.googleapis.com https://cdn-production.discourse.mozilla-community.org 'self' 'unsafe-inline'; connect-src https://discourse.production.paas.mozilla.community https://auth.mozilla.auth0.com https://www.google-analytics.com https://cdn-production.discourse.mozilla-community.org 'self'; font-src https://discourse.production.paas.mozilla.community https://code.cdn.mozilla.net https://fonts.gstatic.com https://fonts.googleapis.com https://cdn-production.discourse.mozilla-community.org 'self' data:; img-src https://discourse.production.paas.mozilla.community https://cdn.auth0.com https://cdn-production.discourse.mozilla-community.org 'self' data: https:;";
