version: 0.2

env:
  parameter-store:
    DB_PWD: "/discourse/dev/db/secret"

phases:
  install:
    runtime-versions:
        ruby: 2.6

  pre_build:
    commands:
      - env
      - echo "aaaaa $ECR"
      - git clone -q https://github.com/discourse/discourse_docker.git
      - cd discourse_docker
      - mkdir -p includes && mkdir -p containers
      - wget --https-only -q https://raw.githubusercontent.com/mozilla/discourse.mozilla.org/staging/discourse_staging.yml -O containers/app.yml
      - wget --https-only -q https://raw.githubusercontent.com/mozilla/discourse.mozilla.org/staging/includes/contribute.yml -O includes/contribute.yml
      - wget --https-only -q https://raw.githubusercontent.com/mozilla/discourse.mozilla.org/staging/includes/headers.yml  -O includes/headers.yml
      # TODO switch to upstream repo when ready
      - wget --https-only -q https://raw.githubusercontent.com/The-smooth-operator/discourse.mozilla.org/master/includes/env.yml -O includes/env.yml

      - sed -i "s/db-host/$DB_HOST/" includes/env.yml
      - sed -i "s/redis-host/$REDIS_HOST/" includes/env.yml
      - sed -i "s/my-non-real-password/$DB_PWD/" includes/env.yml

  build:
    commands:
      - ./launcher bootstrap app 
  post_build:
    commands:
      - docker tag local_discourse/app:latest $ECR:latest
      - docker push $ECR:latest
