version: 0.2

env:
  parameter-store:
    DB_PWD: "/discourse/dev/db/secret"

phases:
  install:
    runtime-versions:
        ruby: 2.6
    commands:
      - aws eks update-kubeconfig --name $CLUSTER 
      - aws ecr get-login --region us-west-2 --no-include-email | bash
      - wget -q https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz
      - wget -q https://get.helm.sh/helm-v2.14.3-linux-amd64.tar.gz.sha256
      - if [[ "$(cat helm-v2.14.3-linux-amd64.tar.gz.sha256)" != "$(sha256sum helm-v2.14.3-linux-amd64.tar.gz | awk '{print $1}')" ]] ; then echo "There was a problem downloading Helm && exit 1" ; fi
      - tar xvf helm-v2.14.3-linux-amd64.tar.gz

  pre_build:
    commands:
      - git clone -q https://github.com/discourse/discourse_docker.git
      - cd discourse_docker
      - mkdir -p includes && mkdir -p containers
      #- wget --https-only -q https://raw.githubusercontent.com/mozilla/discourse.mozilla.org/staging/discourse_staging.yml -O containers/app.yml
      - wget --https-only -q https://raw.githubusercontent.com/The-smooth-operator/discourse.mozilla.org/master/discourse-dev.yml -O containers/app.yml
      - wget --https-only -q https://raw.githubusercontent.com/mozilla/discourse.mozilla.org/staging/includes/contribute.yml -O includes/contribute.yml
      - wget --https-only -q https://raw.githubusercontent.com/mozilla/discourse.mozilla.org/staging/includes/headers.yml  -O includes/headers.yml
      # TODO switch to upstream repo when ready
      - wget --https-only -q https://raw.githubusercontent.com/The-smooth-operator/discourse.mozilla.org/master/includes/env.yml -O includes/env.yml

      - sed -i "s/db-host/$DB_HOST/" includes/env.yml
      - sed -i "s/redis-host/$REDIS_HOST/" includes/env.yml
      - sed -i "s/my-non-real-password/$DB_PWD/" includes/env.yml
      - sed -i "s/discourse-hostname/$D_HOSTNAME/" includes/env.yml
      - sed -i "s/smtp-username/$SMTP_USER/" includes/env.yml
      - sed -i "s/smtp-password/$SMTP_PW/" includes/env.yml

  build:
    commands:
      - ./launcher bootstrap app 
      - cd ..
  post_build:
    commands:
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - docker tag local_discourse/app:latest "$ECR:$CODEBUILD_RESOLVED_SOURCE_VERSION"
      - docker push "$ECR:$CODEBUILD_RESOLVED_SOURCE_VERSION"
      # Deploy
      # TODO: use upstream repo when ready
      - git clone https://github.com/The-smooth-operator/discourse.mozilla.org.git
      - cd discourse.mozilla.org
      - ../linux-amd64/helm template -f k8s/values/dev.yaml --set docker_registry="$ECR",rev="$CODEBUILD_RESOLVED_SOURCE_VERSION" k8s/ | kubectl apply -f -
