version: 0.2

env:
  parameter-store:
    DB_PWD: "/discourse/dev/db/secret"

phases:
  install:
    runtime-versions:
        ruby: 2.6
    commands:
      - aws eks update-kubeconfig --name $CLUSTER 
      - aws ecr get-login --region us-west-2 --no-include-email | bash
      - snap install helm --classic

  pre_build:
    commands:
      - git clone -q https://github.com/discourse/discourse_docker.git
      - cd discourse_docker
      - mkdir -p includes && mkdir -p containers
      - wget --https-only -q https://raw.githubusercontent.com/mozilla/discourse.mozilla.org/staging/discourse_staging.yml -O containers/app.yml
      - wget --https-only -q https://raw.githubusercontent.com/mozilla/discourse.mozilla.org/staging/includes/contribute.yml -O includes/contribute.yml
      - wget --https-only -q https://raw.githubusercontent.com/mozilla/discourse.mozilla.org/staging/includes/headers.yml  -O includes/headers.yml
      # TODO switch to upstream repo when ready
      - wget --https-only -q https://raw.githubusercontent.com/The-smooth-operator/discourse.mozilla.org/master/includes/env.yml -O includes/env.yml

      - sed -i "s/db-host/$DB_HOST/" includes/env.yml
      - sed -i "s/redis-host/$REDIS_HOST/" includes/env.yml
      - sed -i "s/my-non-real-password/$DB_PWD/" includes/env.yml

  build:
    commands:
      #- ./launcher bootstrap app 
  post_build:
    commands:
      #- $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      #- docker tag local_discourse/app:latest "$ECR:latest"
      #- echo "docker push $ECR:latest"
      #- docker push "$ECR:latest"
      # Deploy
      - git clone https://github.com/The-smooth-operator/discourse.mozilla.org.git
      - cd discourse.mozilla.org
      - helm template -f k8s/values/dev.yaml --set docker_registry="$ECR",rev=latest k8s/
