name: discourse
namespace: discourse-dev

# Deployment variables
replicas: 1
arn_role: xxx
revision: release
memory_req: 512Mi
memory_limit: 1024Mi
cpu_req: 0.5
cpu_limit: 1
port: 80

# Docker variables
docker_registry: discourse


