name: discourse
namespace: discourse-prod

# Deployment variables
arn_role: arn:aws:iam::783633885093:role/discourse/discourse-prod
revision: latest
memory_req: 512Mi
memory_limit: 1024Mi
cpu_req: 0.5
cpu_limit: 1
port: 80
ingress_replicas: 1
ssl_cert_arn: arn:aws:acm:us-west-2:783633885093:certificate/0ba01e3b-f733-482c-85f9-e6659d3be9b5

domain_name: discourse.mozilla.org

docker_registry: discourse

# Horizontal autoscaler
hpa_min: 3
hpa_max: 15
hpa_target: 75
